---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart lldpd
  ansible.builtin.service:
    name: 'lldpd'
    state: 'restarted'