---

- name: Manage local machine information
  collections: [ 'progeekro.bootstrap' ]
  hosts: [ 'all_hosts', 'service_machine' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: machine
      tags: [ 'role::machine', 'skip::machine' ]