---

- name: Manage Network Time Protocol service
  collections: [ 'progeekro.bootstrap' ]
  hosts: [ 'all_hosts', 'service_ntp' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ntp
      tags: [ 'role::ntp', 'skip::ntp' ]