---
# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Manage time zone configuration
  collections: [ 'progeekro.bootstrap' ]
  hosts: [ 'all_hosts', 'service_tzdata' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: tzdata
      tags: [ 'role::tzdata', 'skip::tzdata' ]
